[package]
name = "prefix-varint"
version = "0.0.1-alpha.1"
authors = ["Yotam Ofek <yotam.ofek@gmail.com>"]
edition = "2018"
license = "MIT"
description = "PrefixVarint encoding for u64 integers."

[dependencies]
num-traits = "0.2"

[dev-dependencies]
rand = "0.8"
