[package]
name = "prefix-varint"
version = "0.0.1-alpha.4"
authors = ["Yotam Ofek <yotam.ofek@gmail.com>"]
edition = "2018"
license = "MIT"
description = "PrefixVarint encoding for u64 integers."

[dev-dependencies]
rand = "0.8"
